### ISSUE TITLE
ModuleNotFoundError: No module named 'mi'

### ISSUE THREAD

**Issue by ThatOneCalculator** [fotoente/MIsskey-ebooks-bot#21]
I installed from requirements.txt but I keep getting

```
Traceback (most recent call last):
  File "./rdbot.py", line 4, in <module>
    from mi.ext import commands, tasks
ModuleNotFoundError: No module named 'mi'
```

**Comment by ThatOneCalculator** [comment]
Nvm, I had to `pip install git+https://github.com/yupix/Mi.py.git `

**Comment by ThatOneCalculator** [comment]
U

**Comment by ThatOneCalculator** [comment]
After running `pip install mi.py` I now get
```
Traceback (most recent call last):
  File "./rdbot.py", line 4, in <module>
    from mi.ext import commands, tasks
  File "/home/the1calc/.local/lib/python3.8/site-packages/mi/__init__.py", line 11, in <module>
    from .bot import Bot, BotBase
  File "/home/the1calc/.local/lib/python3.8/site-packages/mi/bot.py", line 8, in <module>
    from mi import UserProfile, config
ImportError: cannot import name 'UserProfile' from partially initialized module 'mi' (most likely due to a circular import) (/home/the1calc/.local/lib/python3.8/site-packages/mi/__init__.py)
```
